env:
  DOCKER_IMAGE=matshareyourscript/php-phalcon-node
  DOCKER_TAG=1.0.0

services:
  - docker

script:
  - docker build -t $DOCKER_IMAGE:latest -t $DOCKER_IMAGE:$DOCKER_TAG .
  - docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$DOCKER_TAG

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE:$DOCKER_TAG
  - docker push $DOCKER_IMAGE:latest