env:
  DOCKER_IMAGE=matshareyourscript/php-phalcon-node
  DOCKER_TAG=1.0.0

services:
  - docker

before_install:
  #- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t $DOCKER_IMAGE:latest -t $DOCKER_IMAGE:$DOCKER_TAG .
  - docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$DOCKER_TAG

after_success:
  - docker push $DOCKER_IMAGE:$DOCKER_TAG
  - docker push $DOCKER_IMAGE:latest